name: voice_ai_app
description: A Flutter voice AI application with OpenAI Realtime API integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.0

  # Audio is handled by WebRTC directly

  # WebRTC & HTTP  
  flutter_webrtc: ^0.12.1
  dio: ^5.3.2
  dartz: ^0.10.1

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Environment Configuration
  flutter_dotenv: ^5.1.0

  # Logging
  logger: ^2.0.2+1

  # WebRTC handles permissions automatically

  # UI Components
  cupertino_icons: ^1.0.2
  
  # Text to Speech
  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.0

  # Linting
  flutter_lints: ^3.0.0

  # Testing
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - .env